---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunger
  labels:
    app: hunger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hunger
  template:
    metadata:
      labels:
        app: hunger
    spec:
      containers:
        - name: hunger
          image: docker.io/phengbunath/hunger:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
